/**
 * Turns the GD-1 geometry predictions into `src/db/seed/logitech-descriptors.json`
 * records. Pure: the CLI (scripts/descriptors-from-geometry.ts) reads and writes
 * the files; everything decided here is tested in
 * tests/unit/geometry-descriptors.test.ts.
 *
 * Provenance. GD-1 measured descriptors from the delivered 3D shells. The
 * mapping was pre-registered in commit 06cc13d on origin/geo-descriptors
 * (tools/blender/DESCRIPTOR-GEOMETRY.md there). Run 1, on 2026-10-02 against the
 * Logitech M1 gate (coarse >= 85 % and within-one >= 90 %), gave:
 *
 *   hump        n=29  exact 75.9 %  within-one 93.1 %  coarse 93.1 %  pass
 *   front flare n=28  exact 46.4 %  within-one 75.0 %  coarse 67.9 %  FAIL
 *   curvature   n=28  exact 14.3 %  within-one 67.9 %  coarse 14.3 %  FAIL
 *
 * So only hump placement is applied. Front flare and side curvature stay null
 * whatever the predictions file says, and `convertGeometryPredictions` refuses
 * to be asked for them. The predictions file lives outside the repo (it is our
 * own derived data, but large); its SHA-256 is pinned below so the seed file can
 * be regenerated byte for byte from the same input.
 *
 * G9b INTERACTION. The records written here set shape and handCompatibility to
 * null for the 34 models they list. That is today's database value, so nothing
 * changes now. But scripts/seed.ts treats this file as authoritative for every
 * model it lists, nulls included, so once G9b ships the first-party facts in
 * src/db/seed/logitech-facts.json (#89) those nulls would overwrite them. G9b
 * must merge its facts into this file (and teach this converter to carry them,
 * because it regenerates the whole file), or change the seed's precedence so a
 * null does not overwrite a fact, before it ships.
 *
 * COLUMN LABEL. `applyDescriptors` (seed-rows.ts) stamps descriptor_method
 * "rubric_vision" on every record that is not needsReview. These records
 * therefore carry that label although the hump came from geometry, not vision;
 * `descriptorModel` below holds the real provenance. The enum has no geometry
 * value, and adding one needs a migration, which this change does not make.
 */
import { createHash } from "node:crypto";
import {
  HUMP_PLACEMENTS,
  type HumpPlacement,
} from "../../lib/contracts/descriptors";
import { type DescriptorRecord, slugify } from "./seed-rows";

export const GEOMETRY_BRAND = "Logitech";
/** `geometry-gd1@<pre-registration commit>`: names the method and its frozen protocol. */
export const GEOMETRY_DESCRIPTOR_MODEL = "geometry-gd1@06cc13d";
export const GEOMETRY_CLASSIFIED_AT = "2026-10-02";
/** SHA-256 of the GD-1 run 1 predictions file (38 records), unchanged since measurement. */
export const GEOMETRY_PREDICTIONS_SHA256 =
  "21e7ffcf3e6af66bb492f1bcdffe704a6f672f84c50f7015c54ed25badc5dc37";

/** The one descriptor geometry may set: it passed the M1 gate. */
export const GEOMETRY_APPLIED_FIELDS = ["humpPlacement"] as const;

export const LOWER_CONFIDENCE_NOTE =
  "Limited-view study geometry (lower confidence): the shell was interpolated from limited photographs, so its hump position is less certain.";
export const FORM_FACTOR_NOTES = {
  trackball:
    "Unusual form factor (trackball): its shell is not shaped like a standard mouse, so read the hump with care.",
  vertical:
    "Unusual form factor (vertical): its shell is not shaped like a standard mouse, so read the hump with care.",
} as const;

export class GeometryConversionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GeometryConversionError";
  }
}

export interface ConvertOptions {
  /**
   * The descriptors to copy from the predictions. Defaults to, and may only be,
   * `GEOMETRY_APPLIED_FIELDS`: asking for front flare, side curvature or
   * anything else is refused.
   */
  apply?: readonly string[];
}

export interface ConvertResult {
  records: DescriptorRecord[];
  /** Models whose prediction has no hump (no usable shell): they get no record. */
  skipped: string[];
}

const FORM_FACTOR_KEYS = Object.keys(FORM_FACTOR_NOTES);
const CONFIDENCES = ["reconstructed", "lower", "none"] as const;

const isObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

function assertApplicable(apply: readonly string[]): void {
  if (apply.length === 0) {
    throw new GeometryConversionError(
      "Nothing to apply: humpPlacement is the one descriptor geometry may set.",
    );
  }
  for (const field of apply) {
    if (field === "frontFlare" || field === "sideCurvature") {
      throw new GeometryConversionError(
        `Refusing to apply ${field}: it failed the M1 gate in GD-1 run 1, so it stays null.`,
      );
    }
    if (!(GEOMETRY_APPLIED_FIELDS as readonly string[]).includes(field)) {
      throw new GeometryConversionError(
        `Refusing to apply ${field}: only humpPlacement passed the M1 gate for geometry.`,
      );
    }
  }
}

/** Throws unless the record sets nothing but its hump. */
export function assertOnlyHumpSet(records: readonly DescriptorRecord[]): void {
  const mustBeNull = [
    "shape",
    "handCompatibility",
    "frontFlare",
    "sideCurvature",
    "thumbRest",
    "ringFingerRest",
  ] as const;
  for (const record of records) {
    for (const field of mustBeNull) {
      if (record[field] !== null) {
        throw new GeometryConversionError(
          `${record.model}: ${field} must stay null, geometry only sets humpPlacement.`,
        );
      }
    }
  }
}

/**
 * Converts the parsed GD-1 predictions into descriptor records: one per model
 * with a hump, in the order of the input. Copies `humpPlacement` and nothing
 * else; every other descriptor is written as null whatever the input holds.
 */
export function convertGeometryPredictions(
  input: unknown,
  options: ConvertOptions = {},
): ConvertResult {
  assertApplicable(options.apply ?? GEOMETRY_APPLIED_FIELDS);
  if (!Array.isArray(input)) {
    throw new GeometryConversionError(
      "Predictions must be a JSON array of records.",
    );
  }

  const entries = input.map((entry, index) => {
    if (
      !isObject(entry) ||
      typeof entry.model !== "string" ||
      typeof entry.slug !== "string"
    ) {
      throw new GeometryConversionError(
        `Record ${index}: expected an object with a string model and slug.`,
      );
    }
    if (entry.slug !== slugify(GEOMETRY_BRAND, entry.model)) {
      throw new GeometryConversionError(
        `${entry.model}: slug "${entry.slug}" does not match the model name.`,
      );
    }
    return entry as Record<string, unknown> & { model: string; slug: string };
  });

  const modelBySlug = new Map(entries.map((e) => [e.slug, e.model] as const));
  const seen = new Set<string>();
  const records: DescriptorRecord[] = [];
  const skipped: string[] = [];

  for (const entry of entries) {
    const { model } = entry;
    if (seen.has(model)) {
      throw new GeometryConversionError(`${model}: appears more than once.`);
    }
    seen.add(model);

    if (entry.humpPlacement === null) {
      skipped.push(model);
      continue;
    }
    const hump = entry.humpPlacement;
    if (
      typeof hump !== "string" ||
      !(HUMP_PLACEMENTS as readonly string[]).includes(hump)
    ) {
      throw new GeometryConversionError(
        `${model}: ${JSON.stringify(hump)} is not a hump placement (expected one of ${HUMP_PLACEMENTS.join(", ")}).`,
      );
    }

    const notes: string[] = [];
    if (entry.aliasOf !== undefined) {
      const source =
        typeof entry.aliasOf === "string"
          ? modelBySlug.get(entry.aliasOf)
          : undefined;
      if (source === undefined) {
        throw new GeometryConversionError(
          `${model}: aliasOf ${JSON.stringify(entry.aliasOf)} is not a model in the predictions.`,
        );
      }
      notes.push(
        `Alias of ${source}: its hump is copied from that shell, not an independent geometry observation.`,
      );
    }
    if (
      !(CONFIDENCES as readonly unknown[]).includes(entry.confidence) ||
      entry.confidence === "none"
    ) {
      throw new GeometryConversionError(
        `${model}: a hump needs confidence "reconstructed" or "lower", got ${JSON.stringify(entry.confidence)}.`,
      );
    }
    if (entry.confidence === "lower") notes.push(LOWER_CONFIDENCE_NOTE);
    const caution = entry.frameCaution ?? null;
    if (caution !== null) {
      if (typeof caution !== "string" || !FORM_FACTOR_KEYS.includes(caution)) {
        throw new GeometryConversionError(
          `${model}: unknown frameCaution ${JSON.stringify(caution)}.`,
        );
      }
      notes.push(FORM_FACTOR_NOTES[caution as keyof typeof FORM_FACTOR_NOTES]);
    }

    records.push({
      model,
      shape: null,
      handCompatibility: null,
      humpPlacement: hump as HumpPlacement,
      frontFlare: null,
      sideCurvature: null,
      thumbRest: null,
      ringFingerRest: null,
      sourceImageUrls: [],
      descriptorModel: GEOMETRY_DESCRIPTOR_MODEL,
      classifiedAt: GEOMETRY_CLASSIFIED_AT,
      needsReview: false,
      ...(notes.length > 0 ? { notes } : {}),
    });
  }

  assertOnlyHumpSet(records);
  return { records, skipped };
}

export function sha256Hex(bytes: Uint8Array | string): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/**
 * Parses a predictions file's bytes after checking its SHA-256 against the
 * expected one (the pinned GD-1 run 1 hash unless a caller names another).
 */
export function convertPredictionsFile(
  bytes: Uint8Array,
  options: ConvertOptions & { expectedSha256?: string } = {},
): ConvertResult & { sha256: string } {
  const expected = options.expectedSha256 ?? GEOMETRY_PREDICTIONS_SHA256;
  const sha256 = sha256Hex(bytes);
  if (sha256 !== expected) {
    throw new GeometryConversionError(
      `Predictions SHA-256 is ${sha256}, expected ${expected}. Refusing a file that is not the one the gate was measured on.`,
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(Buffer.from(bytes).toString("utf8"));
  } catch {
    throw new GeometryConversionError("Predictions are not valid JSON.");
  }
  return { ...convertGeometryPredictions(parsed, options), sha256 };
}
