import { describe, expect, it } from "vitest";
import { findMedicalClaimTerm } from "../../src/server/analysis/medicalClaims";

/**
 * Chinese coverage of the medical-claims list (candidate list, 未拍板). The
 * model prompt is English today, but model output can be Chinese (i18n PR3
 * turns it on), so both Traditional and Simplified terms must already be
 * rejected. Categories follow the rule the English list enforces: named
 * conditions, symptoms, injury, treatment and efficacy, prevention and relief
 * claims, and "healthy / ergonomic / friendly to the wrist" claims. Comfort
 * wording ("less fatigue", "comfortable") is deliberately NOT a medical claim
 * in the English list, and stays accepted here too.
 */
const MUST_FLAG: readonly (readonly [category: string, text: string])[] = [
  // Named conditions
  ["condition (TW)", "降低滑鼠手的風險"],
  ["condition (CN)", "降低鼠标手的风险"],
  ["condition (TW)", "不容易得媽媽手"],
  ["condition (CN)", "不容易得妈妈手"],
  ["condition", "有腱鞘炎的人也適合"],
  ["condition (TW)", "避免網球肘"],
  ["condition (CN)", "避免网球肘"],
  ["condition (TW)", "板機指的困擾"],
  ["condition (CN)", "扳机指的困扰"],
  ["condition (TW)", "關節炎患者"],
  ["condition (CN)", "关节炎患者"],
  ["condition (TW)", "重複性勞損"],
  ["condition (CN)", "重复性劳损"],
  ["condition (TW)", "重複性傷害"],
  ["condition (CN)", "重复性伤害"],
  ["condition (TW)", "職業病"],
  ["condition (CN)", "职业病"],
  ["syndrome (TW)", "滑鼠症候群"],
  ["syndrome (CN)", "鼠标综合征"],
  ["syndrome (CN)", "鼠标综合症"],
  ["syndrome (TW)", "滑鼠綜合症"],
  ["syndrome (TW)", "滑鼠綜合徵"],
  ["disease (TW)", "疾病"],
  ["disease", "病症"],
  ["disease", "病痛"],
  ["disease (CN)", "疾病"],
  ["symptom (TW)", "症狀會減少"],
  ["symptom (CN)", "症状会减少"],
  // Symptoms
  ["pain (TW)", "手痛的人"],
  ["pain (CN)", "手痛的人"],
  ["pain", "腕部刺痛"],
  ["pain (TW)", "痠痛"],
  ["pain (TW)", "手臂痠"],
  ["pain", "手疼"],
  ["pain (CN)", "酸痛"],
  ["soreness (TW)", "手酸"],
  ["soreness (TW)", "手痠"],
  ["numbness (TW)", "手麻"],
  ["numbness", "指尖發麻"],
  ["numbness (CN)", "指尖发麻"],
  ["numbness", "麻木"],
  ["numbness (TW)", "麻痺"],
  ["numbness (CN)", "麻痹"],
  ["inflammation (TW)", "發炎"],
  ["inflammation (CN)", "发炎"],
  ["inflammation", "炎症"],
  ["swelling (TW)", "手腕腫脹"],
  ["swelling (CN)", "手腕肿胀"],
  // Injury
  ["injury (TW)", "傷害"],
  ["injury (CN)", "伤害"],
  ["injury (TW)", "損傷"],
  ["injury (CN)", "损伤"],
  ["injury (TW)", "勞損"],
  ["injury (CN)", "劳损"],
  ["injury (TW)", "拉傷"],
  ["injury (CN)", "拉伤"],
  ["injury (TW)", "扭傷"],
  ["injury (CN)", "扭伤"],
  // Treatment and efficacy
  ["efficacy (TW)", "療效"],
  ["efficacy (CN)", "疗效"],
  ["therapy (TW)", "療法"],
  ["therapy (CN)", "疗法"],
  ["therapy (TW)", "療程"],
  ["therapy (CN)", "疗程"],
  ["cure (TW)", "治癒"],
  ["cure (CN)", "治愈"],
  ["cure (TW)", "痊癒"],
  ["cure (CN)", "痊愈"],
  ["recovery (TW)", "康復"],
  ["recovery (CN)", "康复"],
  ["rehabilitation (TW)", "復健"],
  ["rehabilitation (CN)", "复健"],
  ["medicine", "醫學上"],
  ["medicine", "医学上"],
  ["doctor (TW)", "請諮詢醫生"],
  ["doctor (CN)", "请咨询医生"],
  ["doctor (TW)", "醫師"],
  ["doctor (CN)", "医师"],
  ["seek care (TW)", "請就醫"],
  ["seek care (CN)", "请就医"],
  ["clinical (TW)", "臨床證實"],
  ["clinical (CN)", "临床证实"],
  ["drug (TW)", "藥物"],
  ["drug (CN)", "药物"],
  // Prevention and relief
  ["prevent (TW)", "預防損傷"],
  ["prevent (CN)", "预防损伤"],
  ["prevent (TW)", "防止受傷"],
  ["prevent (CN)", "防止受伤"],
  ["prevent (TW)", "避免勞損"],
  ["prevent (CN)", "避免劳损"],
  ["prevent (TW)", "預防疾病"],
  ["prevent (TW)", "預防慢性病"],
  ["prevent (CN)", "预防慢性病"],
  ["prevent (TW)", "避免生病"],
  ["prevent (CN)", "预防疾病"],
  ["prevent (TW)", "防範關節炎"],
  ["prevent (CN)", "防范关节炎"],
  ["prevent (TW)", "預防腕隧道症候群"],
  ["relieve (TW)", "舒緩手腕不適"],
  ["relieve (CN)", "舒缓手腕不适"],
  ["relieve (TW)", "舒緩壓力"],
  ["relieve (CN)", "舒缓压力"],
  ["relieve (TW)", "舒緩手腕疼痛"],
  ["relieve (CN)", "舒缓手腕疼痛"],
  ["relieve (TW)", "舒緩不適"],
  ["relieve (CN)", "舒缓不适"],
  ["relieve (TW)", "舒緩肌肉緊繃"],
  ["relieve (CN)", "舒缓紧绷"],
  ["relieve (TW)", "舒緩疲勞"],
  ["relieve (CN)", "舒缓疲劳"],
  ["relieve (TW)", "舒緩痠痛"],
  ["relieve (CN)", "舒缓症状"],
  // 舒緩 is refused unless a shape noun goes with it (see MUST_PASS below).
  ["relieve (TW)", "舒緩手腕"],
  ["relieve (TW)", "舒緩手部"],
  ["relieve (TW)", "舒緩手指"],
  ["relieve (TW)", "舒緩手掌"],
  ["relieve (TW)", "舒緩肌肉"],
  ["relieve (TW)", "舒緩肩頸"],
  ["relieve (TW)", "舒緩掌心壓力"],
  ["relieve (TW)", "舒緩局部壓力"],
  ["relieve (TW)", "舒緩壓迫感"],
  ["relieve (TW)", "舒緩負擔"],
  ["relieve (TW)", "舒緩負荷"],
  ["relieve (TW)", "舒緩緊張"],
  ["relieve (TW)", "舒緩疲憊"],
  ["relieve (TW)", "舒緩手腕疲勞"],
  ["relieve (TW)", "舒緩長時間使用的疲勞"],
  ["relieve (TW)", "舒緩拇指負擔"],
  ["relieve (TW)", "有助舒緩"],
  ["relieve (TW)", "能舒緩"],
  ["relieve (TW)", "可舒緩"],
  ["relieve (TW)", "幫助舒緩手掌"],
  ["relieve (TW)", "舒緩你的手"],
  ["relieve (CN)", "舒缓手腕"],
  ["relieve (CN)", "舒缓肌肉"],
  ["relieve (CN)", "有助舒缓"],
  ["relieve (CN)", "舒缓你的手"],
  ["relieve (CN)", "舒缓负担"],
  ["relieve (variant)", "紓緩壓力"],
  ["relieve (variant)", "纾缓"],
  ["relieve (variant)", "紓解疲勞"],
  ["relieve (variant)", "纾解"],
  ["relieve (variant)", "抒解壓力"],
  ["relieve (variant)", "舒解疲勞"],
  // A relief claim stays one after a shape noun: what follows 舒緩 counts.
  ["relieve after a shape noun", "弧度舒緩手腕"],
  ["relieve after a shape noun", "弧度舒緩了手腕的壓力"],
  ["relieve after a shape noun", "曲線舒緩的手腕"],
  ["relieve after a shape noun", "弧度舒緩，讓手腕更放鬆"],
  ["relieve after a shape noun", "造型舒緩肌肉"],
  ["relieve after a shape noun", "輪廓舒緩掌心"],
  ["relieve after a shape noun", "弧度舒緩了手部負擔"],
  ["relieve after a shape noun", "弧度很舒緩手腕"],
  ["relieve after a shape noun", "曲线舒缓手腕"],
  ["relieve after a shape noun", "弧度舒緩，減輕疲勞"],
  ["relieve after a shape noun", "側面舒緩肩頸"],
  ["relieve after a shape noun", "隆起舒緩不適"],
  // ...and a word that is not an adverb between the noun and 舒緩 is no
  // description of the shape.
  ["relieve after a verb", "弧度有助舒緩"],
  ["relieve after a verb", "弧度會舒緩"],
  ["relieve after a verb", "弧度能舒緩"],
  ["relieve (TW)", "緩解"],
  ["relieve (CN)", "缓解"],
  ["reduce stress (TW)", "減輕手腕壓力"],
  ["reduce stress (CN)", "减轻手腕压力"],
  ["reduce stress (TW)", "降低手部緊繃"],
  ["reduce stress (CN)", "降低手部紧绷"],
  ["reduce stress (TW)", "減少手指張力"],
  ["reduce stress (CN)", "减少手指张力"],
  ["reduce burden (TW)", "減輕手腕負擔"],
  ["reduce burden (CN)", "减轻手腕负担"],
  ["protect (TW)", "保護手腕"],
  ["protect (CN)", "保护手腕"],
  ["protect (TW)", "呵護關節"],
  ["protect (CN)", "呵护关节"],
  // A lower load on a body part
  ["lower load (TW)", "手腕負擔較小"],
  ["lower load (TW)", "對手腕壓力較低"],
  ["lower load (TW)", "手腕壓力更少"],
  ["lower load (TW)", "肌肉負擔減少"],
  ["lower load (TW)", "手指負擔比較小"],
  ["lower load (TW)", "手臂的負擔較輕"],
  ["lower load (CN)", "关节负担较小"],
  ["lower load (CN)", "对手腕压力较低"],
  // Good for a body part
  ["good for the body (TW)", "有助於手腕"],
  ["good for the body (TW)", "有益身體"],
  ["good for the body (TW)", "有利於關節"],
  ["good for the body (TW)", "有助於肌肉"],
  ["good for the body (TW)", "有助於你的手腕"],
  ["good for the body (TW)", "有助於肩頸"],
  ["good for the body (TW)", "有益於背部"],
  ["good for the body (CN)", "有利于关节"],
  ["good for the hand (TW)", "有助於手部放鬆"],
  ["good for the hand (TW)", "有利於手掌壓力"],
  ["good for the hand (TW)", "有益手指"],
  // Relaxing a body part
  ["relax (TW)", "放鬆手腕"],
  ["relax (TW)", "放鬆肌肉"],
  ["relax (TW)", "放鬆你的手臂"],
  ["relax (CN)", "放松肩颈"],
  ["relax (TW)", "舒展手指"],
  // Preventing discomfort or problems
  ["prevent (TW)", "預防不適"],
  ["prevent (TW)", "避免不適"],
  ["prevent (TW)", "避免手腕不適"],
  ["prevent (TW)", "防止問題"],
  ["prevent (TW)", "避免關節問題"],
  ["prevent (CN)", "预防不适"],
  ["prevent (CN)", "避免手腕问题"],
  // Patients and evidence
  ["patients (TW)", "罹患腕隧道"],
  ["patients (TW)", "患者"],
  ["patients (TW)", "患有關節炎"],
  ["evidence (TW)", "科學證實"],
  ["evidence (CN)", "科学证实"],
  ["evidence (TW)", "研究顯示"],
  ["evidence (CN)", "研究显示"],
  ["evidence (TW)", "專家建議"],
  ["evidence (CN)", "专家建议"],
  // Healthy / ergonomic / friendly claims
  ["health", "有益健康"],
  ["health", "保健"],
  ["health (TW)", "養生"],
  ["health (CN)", "养生"],
  ["wrist-friendly (TW)", "手腕友善"],
  ["wrist-friendly (CN)", "手腕友好"],
  ["wrist-friendly (TW)", "對手腕友善"],
  ["wrist-friendly (CN)", "对手腕友好"],
  ["safer (TW)", "對手腕更安全"],
  ["safer (CN)", "对手腕更安全"],
  ["safer (TW)", "對身體更安全"],
  ["ergonomic (TW)", "人體工學"],
  ["ergonomic (CN)", "人体工学"],
  ["ergonomic (TW)", "人體工程學"],
  ["ergonomic (CN)", "人体工程学"],
  ["ergonomic (TW)", "人因工程"],
  ["ergonomic (CN)", "人机工程"],
  ["ergonomic (TW)", "人機工程設計"],
  ["ergonomic (TW)", "人因工學"],
  ["ergonomic (TW)", "人機工學"],
  ["ergonomic (CN)", "人机工学"],
  ["wrist guard (TW)", "護腕"],
  ["wrist guard (CN)", "护腕"],
];

// Shape facts, comfort wording, and ordinary words that merely share a
// character with a term above.
const MUST_PASS: readonly string[] = [
  "這款滑鼠的長度與你的手很搭。",
  "这款鼠标的长度与你的手很搭。",
  "前端向外擴張，適合爪握。",
  "前端向外扩张，适合爪握。",
  "拱背偏高，掌握時手心貼合。",
  "拱背偏高，掌握时手心贴合。",
  "重量較輕，握起來很順手。",
  "外殼比你的手寬，握持面較窄。",
  "不對稱造型，僅供右手使用。",
  "不对称造型，仅供右手使用。",
  "握起來舒適，長時間使用也不容易疲勞。", // comfort, like the English "less fatigue"
  "握起来舒适，长时间使用也不容易疲劳。",
  "預防滑動", // "prevents sliding": existing near miss
  "预防滑动",
  "避免手指打滑",
  "避免手指打滑，握持更穩。",
  "降低高度以配合你的手掌。",
  "降低整體高度",
  "減輕重量",
  "减轻重量",
  "減少重量",
  "改善握感",
  "保護套",
  "保护套",
  "手腕位置",
  "手腕寬度",
  "疼愛",
  "疼爱",
  "疼惜",
  "改善手指抓握",
  "減少手指打滑",
  "减少手指打滑",
  "麻煩",
  "麻烦",
  "麻辣",
  "酸性塗層",
  "傷腦筋",
  "伤脑筋",
  "健身",
  "安全的購買",
  // A gentle curve with an adverb in between (up to two, three characters).
  "弧度很舒緩",
  "曲線比較舒緩",
  "弧度相當舒緩",
  "弧度是舒緩的",
  "弧度都很舒緩",
  "側面弧度非常舒緩",
  "曲线比较舒缓",
  "弧度十分舒緩",
  "弧度稍微舒緩一些",
  // More shape nouns.
  "弧線舒緩",
  "曲度舒緩",
  "背脊舒緩",
  "尾端舒緩",
  "側裙舒緩",
  "斜坡舒緩",
  "隆起舒緩",
  "凹陷舒緩",
  "側面舒緩",
  // The back of the mouse is not a body part: the body-part words are only
  // looked for in the eight characters after 舒緩.
  "曲線舒緩的背部剛好托住掌心，手指的位置也很自然",
  "弧度舒緩，拇指放起來很自然",
  "弧度舒緩ABCDEFG手腕",
  // A gentle curve: 舒緩 with a shape noun in front, or 的 and a shape noun
  // after it. Nothing else may follow 舒緩.
  "側面弧度舒緩",
  "造型舒緩",
  "輪廓舒緩的前端",
  "线条舒缓",
  "起伏舒緩",
  "坡度舒緩",
  "曲面舒緩",
  "弧面舒緩，拇指好放",
  "舒緩的弧面",
  "舒緩的造型",
  "舒缓的曲线",
  // Ordinary shape and grip statements next to the words the new claim
  // patterns look for.
  "減少握持時的滑動",
  "避免誤觸",
  "避免誤觸問題",
  "避免打滑問題",
  "預留空間",
  "預留空間給拇指",
  "有助於握持",
  "有助於手指抓握",
  "有利於手掌貼合",
  "有助於手指發力",
  "有益於單手操作",
  "放鬆握持也不容易滑",
  "手腕位置自然",
  "重量負擔較小",
  "防止誤觸",
  "這款滑鼠的研究與設計團隊",
  // 舒緩 / 舒缓 on its own is a shape word (a gentle curve), not a claim.
  "弧度舒緩",
  "弧度舒缓",
  "曲線舒緩的背部",
  "曲线舒缓的背部",
  "側邊的弧面舒緩，拇指好放",
  "舒緩的曲線",
  "資料安全",
  "這個排名為暫定，部分形狀描述尚未分類。",
  "这个排名为暂定，部分形状描述尚未分类。",
];

describe("findMedicalClaimTerm — Chinese", () => {
  it.each(MUST_FLAG)("flags %s: %s", (_category, text) => {
    expect(findMedicalClaimTerm(text)).not.toBeNull();
  });

  it.each(MUST_PASS)("accepts shape and comfort wording: %s", (text) => {
    expect(findMedicalClaimTerm(text)).toBeNull();
  });

  it("names the entry that matched, including ones another entry would also catch", () => {
    const labels: readonly (readonly [string, RegExp])[] = [
      ["重複性勞損", /重複性/],
      ["重复性伤害", /重複性|重复性/],
      ["病痛", /^病痛$/],
      ["痠痛", /^痠痛$/],
      ["手臂痠", /痠/],
      ["手疼", /疼/],
      ["舒緩壓力", /^舒緩\/舒缓 pressure/],
      ["舒缓压力", /^舒緩\/舒缓 pressure/],
      ["預防慢性病", /預防/],
    ];
    for (const [text, label] of labels) {
      expect(findMedicalClaimTerm(text), text).toMatch(label);
    }
  });

  it("returns a readable label naming what matched", () => {
    expect(findMedicalClaimTerm("降低滑鼠手的風險")).toBe("滑鼠手");
    expect(findMedicalClaimTerm("預防疾病")).toMatch(/預防|预防/);
  });

  it("flags a Traditional and a Simplified spelling of the same claim alike", () => {
    const pairs: readonly (readonly [string, string])[] = [
      ["治療", "治疗"],
      ["緩解", "缓解"],
      ["人體工學", "人体工学"],
      ["減輕手腕壓力", "减轻手腕压力"],
      ["保護手腕", "保护手腕"],
      ["復健", "复健"],
      ["發炎", "发炎"],
      ["預防損傷", "预防损伤"],
    ];
    for (const [traditional, simplified] of pairs) {
      expect(findMedicalClaimTerm(traditional), traditional).not.toBeNull();
      expect(findMedicalClaimTerm(simplified), simplified).not.toBeNull();
    }
  });
});
